import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar/AppSidebar";
import fetchPropertyData from "@/lib/fetchPropertyData";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const restaurantData = await fetchPropertyData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          {/* サイドバーをモバイル版のみ出現 */}
          <div className="md:hidden">
            <AppSidebar />
          </div>

          <div className="w-full min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer restaurantData={restaurantData} />
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
